### ISSUE TITLE
Do you need /pages/page-name

### ISSUE THREAD

**Issue by jneubauer** [NicholasEli/skeleton-cms#4]
it makes sense to have /modules/page-name/module-name.php, because the modules are grouped by pages, so having a directory of modules per page makes sense.

But all the pages are the same, just one file with the unique page name. Do you need that intermediary directory with the page-name?

Doesn't really change functionality much, just an architectural question.

**Comment by NicholasEli** [comment]
No it doesn't matter necessarily, I thought I was just being organized.  I was thinking maybe in the future maybe sub themes or any template overrides would also sit  in that part of the directory with the parent page.

**Comment by jneubauer** [comment]
ooh, good point, hadn't thought about that.

I'd just be worried about having so many template files or places you have to update for even minor style or script changes (see my comment on #1 about that, where each page means a new place you have to update if you ever want to add a new style sheet, etc)

**Comment by NicholasEli** [comment]
I think I will do how I did for navigation,  new stylesheets and script files will be on an include file.  User can upload. then an include file will scan a directory for all files in that directory.

**Comment by jneubauer** [comment]
![Awesome](http://m.memegen.com/undzf8.jpg)
